# config.yaml
paths:
  folder_path: "C:/Users/ahmed/Desktop/Data_pfad/2023/ltmp_rech"
  input_folder_path: "E:/Masterarbeit_zip"
  low_cut: "C:/Users/ahmed/Desktop/Masterarbeit_alt/Hilfs_dateien_berechnungen/lowcut.xlsx"
  kwid_region_map: "C:/Users/ahmed/Desktop/Data_pfad/2023/helping_files/kwid_reg_mapping.xlsx"
export_yearly_prices_to_excel:
  'yes'
TECH_TO_ABBR:
 LFSolarPV: "pv"
 Wind_Onshore: "wind_on"
 Wind_Offshore: "wind_off"
 CSP_noStorage: "csp"

years:
  start_year: 1992
  end_year: 1992

region_zone_mapping:
  Germany:
    Wind_Onshore:
      kwid_shape_a: 4748
      kwid_shape_b: 4732


    Wind_Offshore:
      kwid_shape_a: 4746
      kwid_shape_b: 4784


    LFSolarPV:
      kwid: 4832


  Baltics:
    Wind_Onshore:
      kwid_shape_a: 4782
      kwid_shape_b: 4733

    Wind_Offshore:
      kwid_shape_a: 275
      kwid_shape_b: null

    LFSolarPV:
      kwid: 4866


  Turkey:
    Wind_Onshore:
      kwid_shape_a: 4767
      kwid_shape_b: 4735


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4852



  Balkans:
    Wind_Onshore:
      kwid_shape_a: 4773
      kwid_shape_b: 4736


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4857


  France:
    Wind_Onshore:
      kwid_shape_a: 4739
      kwid_shape_b: 4737


    Wind_Offshore:
      kwid_shape_a: 4738
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4823



  Belgium:
    Wind_Onshore:
      kwid_shape_a: 4716
      kwid_shape_b: 4742


    Wind_Offshore:
      kwid_shape_a: 4717
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4802



  Austria:
    Wind_Onshore:
      kwid_shape_a: 4734
      kwid_shape_b: 4745


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4819



  Switzerland:
    Wind_Onshore:
      kwid_shape_a: 4722
      kwid_shape_b: 4747


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4806



  Netherlands:
    Wind_Onshore:
      kwid_shape_a: 4770
      kwid_shape_b: 4750


    Wind_Offshore:
      kwid_shape_a: 4771
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4855

  Poland:
    Wind_Onshore:
      kwid_shape_a: 4796
      kwid_shape_b: 4751


    Wind_Offshore:
      kwid_shape_a: 4794
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4878



  Czech Republic:
    Wind_Onshore:
      kwid_shape_a: 4731
      kwid_shape_b: 4753

    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4817



  DenmarkWest:
    Wind_Onshore:
      kwid_shape_a: 4740
      kwid_shape_b: 4754


    Wind_Offshore:
      kwid_shape_a: 4741
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4824



  DenmarkEast:
    Wind_Onshore:
      kwid_shape_a: 4743
      kwid_shape_b: 4756


    Wind_Offshore:
      kwid_shape_a: 4744
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4827



  SloCro:
    Wind_Onshore:
      kwid_shape_a: 4764
      kwid_shape_b: 4760

    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null

    LFSolarPV:
      kwid: 4848


  SWE1and2:
    Wind_Onshore:
      kwid_shape_a: 4761
      kwid_shape_b: 4762

    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null

    LFSolarPV:
      kwid: 4845

  IT_CN:
    Wind_Onshore:
      kwid_shape_a: 4715
      kwid_shape_b: 4718


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 3678


  England:
    Wind_Onshore:
      kwid_shape_a: 4776
      kwid_shape_b: 4763


    Wind_Offshore:
      kwid_shape_a: 4777
      kwid_shape_b: 4786


    LFSolarPV:
      kwid: 4861



  IT_N1:
    Wind_Onshore:
      kwid_shape_a: 4781
      kwid_shape_b: 4714


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null

    LFSolarPV:
      kwid: 4865

  Spain:
    Wind_Onshore:
      kwid_shape_a: 4721
      kwid_shape_b: 4765


    Wind_Offshore:
      kwid_shape_a: 955
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4803


    CSP_noStorage:
      kwid: 4805



  Romania:
    Wind_Onshore:
      kwid_shape_a: 4725
      kwid_shape_b: 4766


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4809

  Slovakia:
    Wind_Onshore:
      kwid_shape_a: 4749
      kwid_shape_b: 4768


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4833

  Hungary:
    Wind_Onshore:
      kwid_shape_a: 4788
      kwid_shape_b: 4769


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4872



  Bulgaria:
    Wind_Onshore:
      kwid_shape_a: 4713
      kwid_shape_b: 4772


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4797



  Greece:
    Wind_Onshore:
      kwid_shape_a: 4752
      kwid_shape_b: 4774


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4838



  Portugal:
    Wind_Onshore:
      kwid_shape_a: 4730
      kwid_shape_b: 4775


    Wind_Offshore:
      kwid_shape_a: 1830
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4812


  Norway:
    Wind_Onshore:
      kwid_shape_a: 4785
      kwid_shape_b: 4778


    Wind_Offshore:
      kwid_shape_a: 1639
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4869



  Finland:
    Wind_Onshore:
      kwid_shape_a: 4791
      kwid_shape_b: 4779


    Wind_Offshore:
      kwid_shape_a: 64
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4875


  IT_CS:
    Wind_Onshore:
      kwid_shape_a: 4719
      kwid_shape_b: 4720


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 3295


  SWE3:
    Wind_Onshore:
      kwid_shape_a: 4755
      kwid_shape_b: 4780


    Wind_Offshore:
      kwid_shape_a: 4757
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4839



  SWE4:
    Wind_Onshore:
      kwid_shape_a: 4758
      kwid_shape_b: 4783


    Wind_Offshore:
      kwid_shape_a: 4759
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4843

  IT_S:
    Wind_Onshore:
      kwid_shape_a: 4723
      kwid_shape_b: 4724


    Wind_Offshore:
      kwid_shape_a: 1646
      kwid_shape_b: null


    LFSolarPV:
      kwid: 3675



  IT_SI:
    Wind_Onshore:
      kwid_shape_a: 4726
      kwid_shape_b: 4727


    Wind_Offshore:
      kwid_shape_a: 1642
      kwid_shape_b: null


    LFSolarPV:
      kwid: 4863



  IT_SA:
    Wind_Onshore:
      kwid_shape_a: 4728
      kwid_shape_b: 4729


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 2923

  IT_CA:
    Wind_Onshore:
      kwid_shape_a: 679
      kwid_shape_b: 1289


    Wind_Offshore:
      kwid_shape_a: null
      kwid_shape_b: null


    LFSolarPV:
      kwid: 663
